apiVersion: apps/v1
kind: Deployment
metadata:
  name: joao-marcos-rule-recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joao-marcos-rule-recommendation
  template:
    metadata:
      labels:
        app: joao-marcos-rule-recommendation
    spec:
      volumes:
        - name: dataset
          hostPath:
            path: /home/datasets/
        - name: project2-pv-joaodepollo
          persistentVolumeClaim:
            claimName: project2-pv-joaodepollo
      containers:
        - name: api-recommendation
          image:  joaovitorsd/tp-cloud-comp-rules-gen:latest
          volumeMounts:
            - name: project2-pv-joaodepollo
              mountPath: /usr/src
            - name: dataset
              mountPath: /home/dataset